### PR TITLE
Add "Contribute" section to the docs

### PR DESCRIPTION
**Pull request by haochizzle**

### CODE REVIEW

**Review by sneakzttv — APPROVED** [review]
looks good to me! Will let @nftpixels merge and delete so he has that process down

**Comment by nftpixels** [comment]
All done! 

Merge completed - Branch deleted.

**Review by nftpixels — COMMENTED** [review]
Approving changes.

**Comment by haochizzle** [comment]
Closes: [Issue #129](https://github.com/ChainSafe/devrel/issues/129)

**Pull request merged**
