### PR TITLE
added RPC setup documentation + reorganized Getting Started / Installation sections

### PR DESCRIPTION
**Pull request by haochizzle**
I spoke with @alexvotofuture about placement of RPC node setup docs and the convo ended up developing into a mini-overhaul of the docs. I advised him this would likely be a devrel epic which would constitute a major refactor of the docs.

He conceded, but would still like the following changes made so the docs make more logical sense:

- [x] At the head of the umbrella, documentation headings (where it says SDK Documentation and Legacy Documentation headings) should include "1.x" and "2.x" next to the titles 

- [x] "Getting Started" renamed to "Migrating from legacy 1.x to v2" and moved somewhere else instead of placing it at the start of the docs

- [x] "Creating Project ID" and new "RPC node setup" docs has to be placed before "Installation" section

- [x] Under "Installation", add a disclaimer near the end of installation to say see docs for "Project ID registration" and "RPC node setup" to properly configure SDK for use

- [x] Add info section for "Project ID registration" that says this guide is for projects that haven't created a project ID yet + and is requirement to use SDK

closes[#173](https://github.com/ChainSafe/devrel/issues/173)

### CODE REVIEW

**Comment by alexvotofuture** [comment]
All changes appear to match what I was suggesting. Thanks so much for the shifts around this RPC provider page - it will help put that page into context, and overall improve readability for first-time users.

Ready to merge from my perspective!

**Review by alexvotofuture — APPROVED** [review]
I'm not sure if there's a way for me to preview what these changes will look like in some kind of staging environment for the docs, but from my casual review of the raw file changes and Tim's overview of our conversations this looks good to me!

**Comment by alexvotofuture** [comment]
@nftpixels I'll leave it to you to merge

**Review by nftpixels — COMMENTED** [review]
All done!

**Pull request merged**
